# infra/envs/minikube/cert-manager-values.yaml
# Overrides específicos para cert-manager en Minikube

extraObjects:
  # ClusterIssuer que genera un CA auto firmado
  - |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: selfsigned
    spec:
      selfSigned: {}

  # Certificado CA usando el issuer selfsigned
  - |
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: local-ca
      namespace: cert-manager
    spec:
      isCA: true
      commonName: local-ca
      secretName: local-ca
      issuerRef:
        name: selfsigned
        kind: ClusterIssuer

  # ClusterIssuer que usa el CA generado previamente
  - |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: local-ca-issuer
    spec:
      ca:
        secretName: local-ca

  # Certificado wildcard para el entorno local
  - |
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: wildcard-minikube
      namespace: traefik
    spec:
      secretName: wildcard-minikube-tls
      dnsNames:
        - '*.127.0.0.1.nip.io'
      issuerRef:
        name: local-ca-issuer
        kind: ClusterIssuer
