# infra/envs/minikube/hello-values.yaml
# Overrides específicos para la aplicación hello en Minikube

replicaCount: 1

ingress:
  hosts:
    - host: hello.127.0.0.1.nip.io

app:
  message: "¡Hola desde Minikube!" 