# infra/envs/minikube/hello-values.yaml
# Environment-specific overrides for hello app in Minikube

replicaCount: 1

ingress:
  hosts:
    - host: hello.{{ .Values.network.domain }}

# Traefik configuration using wildcard certificate
traefik:
  ingressRoute:
    tlsSecret: wildcard-minikube-tls

app:
  message: "¡Hola desde {{ .Values.environment.name | title }}!"
