# infra/envs/minikube/hello-values.yaml
# Environment-specific overrides for hello app in Minikube

replicaCount: 1

ingress:
  hosts:
    - host: hello.127.0.0.1.nip.io

# Traefik configuration using wildcard certificate
traefik:
  ingressRoute:
    tlsSecret: wildcard-minikube-tls

app:
  message: "¡Hola desde Minikube!" 