# .pre-commit-config.yaml
# Pre-commit hooks for automatic code quality fixes

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace  # Auto-fix trailing spaces
        exclude: '^infra/rendered/'
      - id: end-of-file-fixer   # Auto-fix no new line at end of file
        exclude: '^infra/rendered/'
      - id: mixed-line-ending   # Ensure consistent line endings
        exclude: '^infra/rendered/'
      - id: check-yaml           # Basic YAML syntax validation
        exclude: '^infra/rendered/|.*helmfile\.yaml$|.*crds/.*\.yaml$|.*bootstrap/.*\.yaml$|.*rbac/.*\.yaml$|.*templates/.*\.yaml$'
      - id: check-added-large-files  # Prevent large files from being committed
      - id: check-case-conflict  # Check for case conflicts
      - id: check-merge-conflict # Check for merge conflict markers

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--config-file, .yamllint.yml]
        exclude: '^infra/rendered/'

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: \.(sh|bash)$
        exclude: '^infra/rendered/'

# CI skip - pre-commit auto-fixes
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [shellcheck]  # Skip shellcheck in CI (can be slow) 