# infra/apps/helmfile.yaml
# Helmfile raíz que incluye todas las aplicaciones

environments:
  minikube:
    values:
      - ../envs/minikube/global-values.yaml
  netcup:
    values:
      - ../envs/netcup/global-values.yaml

---

repositories:
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  # Incluir Traefik primero (sync-wave: 1)
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: 36.3.0
    values:
      - traefik/values.yaml
      - ../envs/{{ .Environment.Name }}/traefik-values.yaml
    wait: true
    timeout: 300
    atomic: true

  # Incluir Hello después de Traefik (sync-wave: 2)
  - name: hello
    namespace: traefik
    createNamespace: true
    chart: ../charts/hello
    version: 0.1.0
    values:
      - hello/values.yaml
      - ../envs/{{ .Environment.Name }}/hello-values.yaml
    wait: true
    timeout: 300
    atomic: true
    needs:
      - traefik  