# infra/apps/helmfile.yaml
# Helmfile raíz que incluye todas las aplicaciones

environments:
  minikube:
    values:
      - ../envs/minikube/global-values.yaml
  netcup:
    values:
      - ../envs/netcup/global-values.yaml

helmfiles:
  # El orden **define** el sync-wave global
  - path: ./cert-manager/helmfile.yaml   # wave 0
  - path: ./traefik/helmfile.yaml        # wave 1
  - path: ./hello/helmfile.yaml          # wave 2
