# infra/apps/helmfile.yaml
# Helmfile raíz que incluye todas las aplicaciones

environments:
  minikube:
    values:
      - ../envs/minikube/global-values.yaml
  netcup:
    values:
      - ../envs/netcup/global-values.yaml

helmfiles:
  # El orden **define** el sync-wave global
  - path: ./cert-manager/helmfile.yaml   # wave 0
  - path: ./traefik/helmfile.yaml        # wave 1
  - path: ./hello/helmfile.yaml          # wave 2

# ---

# repositories:
#   - name: jetstack              # ← NUEVO repo para cert-manager
#     url: https://charts.jetstack.io
#   - name: traefik
#     url: https://traefik.github.io/charts

# releases:

#   - name: cert-manager
#     namespace: cert-manager
#     createNamespace: true
#     chart: jetstack/cert-manager
#     version: v1.18.2                 # fija siempre la versión
#     values:
#       - cert-manager/values.yaml     # valores base (crds.enabled: false)
#       - ../envs/{{ .Environment.Name }}/cert-manager-values.yaml
#     wait: true
#     timeout: 300
#     atomic: true
#   # Incluir Traefik primero (sync-wave: 1)
#   - name: traefik
#     namespace: traefik
#     createNamespace: true
#     chart: traefik/traefik
#     version: 36.3.0
#     values:
#       - traefik/values.yaml
#       - ../envs/{{ .Environment.Name }}/traefik-values.yaml
#     wait: true
#     timeout: 300
#     atomic: true
#     needs:
#       - cert-manager

#   # Incluir Hello después de Traefik (sync-wave: 2)
#   - name: hello
#     namespace: traefik
#     createNamespace: true
#     chart: ../charts/hello
#     version: 0.1.0
#     values:
#       - hello/values.yaml
#       - ../envs/{{ .Environment.Name }}/hello-values.yaml
#     wait: true
#     timeout: 300
#     atomic: true
#     needs:
#       - traefik  