# infra/apps/helmfile.yaml
# Helmfile raíz que incluye todas las aplicaciones

environments:
  minikube:
    values:
      - ../envs/minikube/global-values.yaml
  netcup:
    values:
      - ../envs/netcup/global-values.yaml

helmfiles:
  # El orden **define** el sync-wave global
  - path: ./cert-manager/helmfile.yaml.gotmpl   # wave 0
  - path: ./sealed-secrets/helmfile.yaml.gotmpl # wave 0 (después de cert-manager)
  - path: ./traefik/helmfile.yaml.gotmpl        # wave 1
  - path: ./hello/helmfile.yaml.gotmpl          # wave 2
