apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/argocd-ingressroute.yaml
  - traefik/argocd-application.yaml
  - hello/argocd-application.yaml

patches:
  - target:
      kind: Application
      name: traefik
    patch: |-
      - op: replace
        path: /spec/source/helm/valueFiles/1
        value: ../../../envs/minikube/traefik-values.yaml
      - op: replace
        path: /spec/source/helm/extraObjects/0/spec/routes/0/match
        value: Host(`traefik.127.0.0.1.nip.io`)
      - op: replace
        path: /spec/source/helm/extraObjects/0/spec/entryPoints
        value: ["web", "websecure"]

  - target:
      kind: Application
      name: hello
    patch: |-
      - op: replace
        path: /spec/source/helm/valueFiles/1
        value: ../../../envs/minikube/hello-values.yaml 