apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/argocd-ingressroute.yaml
  - traefik/argocd-application.yaml
  - hello/argocd-application.yaml

# Nota: Los values específicos de netcup se cargan directamente en las ArgoCD Applications
# usando valueFiles, por lo que no necesitamos patches aquí 