{{- if .Values.traefik.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "hello.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.traefik.ingressRoute.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ (index .Values.ingress.hosts 0).host }}`)
      kind: Rule
      services:
        - name: {{ include "hello.fullname" . }}
          port: {{ .Values.service.port }}
  {{- if .Values.traefik.ingressRoute.certResolver }}
  tls:
    certResolver: {{ .Values.traefik.ingressRoute.certResolver }}
  {{- else if .Values.traefik.ingressRoute.tlsSecret }}
  tls:
    secretName: {{ .Values.traefik.ingressRoute.tlsSecret }}
  {{- end }}
{{- end }} 