apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello.fullname" . }}-test
  labels:
    {{- include "hello.labels" . | nindent 4 }}
    app.kubernetes.io/component: test
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hello.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: test
  template:
    metadata:
      labels:
        {{- include "hello.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: test
    spec:
      containers:
        - name: {{ .Chart.Name }}-test
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }} 