apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello.fullname" . }}-test
  labels:
    {{- include "hello.labels" . | nindent 4 }}
    app.kubernetes.io/component: test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: test 