apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/argocd-ingressroute.yaml
  - traefik/argocd-application.yaml
  - traefik/traefik-dashboard-ingressroute.yaml
  - hello/argocd-application.yaml

# Configuración base para netcup (producción)
# Los values específicos de netcup se cargan directamente en las ArgoCD Applications
# usando valueFiles, por lo que no necesitamos patches aquí 