releases:
  - name: hello
    namespace: traefik
    createNamespace: true
    chart: ../../charts/hello
    version: 0.1.0
    values:
      - values.yaml
      - ../../envs/minikube/hello-values.yaml
    wait: true
    timeout: 300
    atomic: true 