environments:
  minikube: {}
  netcup: {}

---
releases:
  - name: hello
    namespace: traefik
    createNamespace: true
    chart: ../../charts/hello
    version: 0.1.0
    values:
      - values.yaml
      - ../../envs/{{ .Environment.Name }}/hello-values.yaml