# Default values for hello chart
replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: ""
  pullPolicy: IfNotPresent

# Configuración de recursos
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 5678

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: hello.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: hello-tls
      hosts:
        - hello.127.0.0.1.nip.io

# Traefik IngressRoute configuration
traefik:
  ingressRoute:
    enabled: true
    entryPoints:      
      - websecure    
  
  httpIngressRoute:
    enabled: false
    entryPoints:
      - web

# Application specific settings
app:
  message: "¡Hola desde Minikube!" 