apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Después de CRDs
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 24.0.0
    helm:
      valueFiles:
        - ../../apps/traefik/values.yaml
        - ../../envs/netcup/traefik-values.yaml
      extraObjects:
        - apiVersion: traefik.containo.us/v1alpha1
          kind: IngressRoute
          metadata:
            name: traefik-dashboard
            namespace: traefik
          spec:
            entryPoints:
              - websecure
            routes:
              - match: Host(`traefik.albertperez.dev`)
                kind: Rule
                services:
                  - name: api@internal
                    kind: TraefikService
            tls:
              certResolver: le
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 