environments:
  minikube: {}
  netcup: {}

---
repositories:
  - name: traefik
    url: https://traefik.github.io/charts 

releases:
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: 36.3.0
    values:
      - values.yaml
      - ../../envs/{{ .Environment.Name }}/traefik-values.yaml
    wait: true
    timeout: 600
    atomic: true

