releases:
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: 36.3.0
    values:
      - values.yaml
      - ../../envs/{{ .Environment.Name }}/traefik-values.yaml
    wait: true
    timeout: 300
    atomic: true

repositories:
  - name: traefik
    url: https://traefik.github.io/charts 