# infra/envs/netcup/hello-values.yaml
# Overrides específicos para la aplicación hello en Netcup

replicaCount: 2

ingress:
  hosts:
    - host: hello.albertperez.dev

app:
  message: "¡Hola desde Netcup!" 