# infra/envs/netcup/hello-values.yaml
# Environment-specific values for hello app in production (netcup)

replicaCount: 2

ingress:
  hosts:
    - host: hello.{{ .Values.network.domain }}

# Traefik configuration using production wildcard certificate
traefik:
  ingressRoute:
    tlsSecret: wildcard-netcup-tls

app:
  message: "¡Hola desde {{ .Values.environment.name | title }}!" 