# infra/envs/netcup/hello-values.yaml
# Environment-specific values for hello app in production (netcup)

replicaCount: 2

route:
  hostname: hello.albertperez.dev

app:
  message: "¡Hola desde Netcup!"
