# infra/envs/netcup/hello-values.yaml
# Overrides específicos para la aplicación hello en Netcup

replicaCount: 2

image:
  repository: hashicorp/http-echo
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5678

ingress:
  enabled: true
  hosts:
    - host: hello.yourdomain.com  # Cambiar por tu dominio real
      paths:
        - path: /
          pathType: Prefix

traefik:
  ingressRoute:
    enabled: true
    entryPoints:
      - web
      - websecure
    certResolver: le
  
  httpIngressRoute:
    enabled: false

app:
  message: "¡Hola desde Netcup!" 