# infra/envs/netcup/hello-values.yaml
# Valores específicos para la aplicación hello en producción (netcup)

# infra/envs/minikube/hello-values.yaml
# Overrides específicos para la aplicación hello en Minikube

replicaCount: 1

ingress:
  hosts:
    - host: hello.albertperez.dev  

app:
  message: "¡Hola desde Netcup!" 