# infra/envs/netcup/traefik-values.yaml
# Valores específicos para producción (netcup)

global:
  domain: "albertperez.dev"               # tu FQDN real

ingressRoute:
  dashboard:
    matchRule: >
      Host(`traefik.albertperez.dev`)
      && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    tls:
      secretName: traefik-dashboard-cert   # el cert-manager de prod

# Configuraciones específicas de producción
persistence:
  enabled: true
  path: /data
  size: 128Mi

additionalArguments:
  - "--certificatesresolvers.le.acme.httpchallenge=true"
  - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
  - "--certificatesresolvers.le.acme.email=albert@albertperez.dev"
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"

ports:
  websecure:
    tls:
      certResolver: "le"
    expose:
      enabled: true
      exposedPort: 443
      protocol: TCP
