# infra/envs/netcup/traefik-values.yaml
# Valores específicos para producción (netcup)

global:
  domain: "albertperez.dev"               # tu FQDN real

# tlsStore:
#   default:
#     defaultCertificate:
#       secretName: "wildcard-netcup-tls"   # el Secret creado por cert-manager

ingressRoute:
  dashboard:
    matchRule: >
      Host(`traefik.albertperez.dev`)
      && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    # middlewares:
    #   - name: basic-auth
    #     namespace: admin
