# infra/envs/netcup/traefik-values.yaml
# Valores específicos para producción (netcup)

# Configuración del dashboard de Traefik
ingressRoute:
  dashboard:
    # Exponer dashboard en traefik.albertperez.dev
    entryPoints: ["web", "websecure"]
    # Configurar TLS con Let's Encrypt
    tls: {}

persistence:
  enabled: true
  path: /data
  size: 128Mi

additionalArguments:
  - "--certificatesresolvers.le.acme.httpchallenge=true"
  - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
  - "--certificatesresolvers.le.acme.email=albert@albertperez.dev"  # Email real para Let's Encrypt
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"  # Producción, no staging

ports:
  websecure:
    tls:
      certResolver: "le"  # Usar Let's Encrypt en producción
