# infra/envs/netcup/traefik-values.yaml
# Environment-specific values for production (netcup)

ingressRoute:
  dashboard:
    matchRule: >
      Host(`traefik.albertperez.dev`)
      && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    middlewares:
      - name: basic-auth
        namespace: admin

extraObjects:
  # Wildcard certificate for production domain
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: wildcard-netcup
      namespace: traefik
    spec:
      secretName: wildcard-netcup-tls
      dnsNames:
        - '*.albertperez.dev'
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer

# Listener HTTPS del Gateway con el certificado wildcard de producción
gateway:
  listeners:
    websecure:
      port: 8443
      protocol: HTTPS
      mode: Terminate
      namespacePolicy:
        from: All
      certificateRefs:
        - name: wildcard-netcup-tls

tlsStore:
  default:
    defaultCertificate:
      secretName: "wildcard-netcup-tls"
