# infra/envs/netcup/traefik-values.yaml
# Valores específicos para producción (netcup)

global:
  domain: "albertperez.dev"               # tu FQDN real

# tlsStore:
#   default:
#     defaultCertificate:
#       secretName: "wildcard-netcup-tls"   # el Secret creado por cert-manager

ingressRoute:
  dashboard:
    matchRule: >
      Host(`traefik.albertperez.dev`)
      && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    # middlewares:
    #   - name: basic-auth
    #     namespace: admin


extraObjects:
  # Certificado wildcard para el dominio principal
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: wildcard-netcup
    spec:
      secretName: wildcard-netcup-tls
      dnsNames:
        - '*.albertperez.dev'
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer

tlsStore:
  default:
    defaultCertificate:
      secretName: "wildcard-netcube-tls"                