# infra/envs/netcup/traefik-values.yaml
# Environment-specific values for production (netcup)

# Inherit from global values
network:
  domain: "albertperez.dev"

global:
  domain: "albertperez.dev"

ingressRoute:
  dashboard:
    matchRule: >
      Host(`traefik.albertperez.dev`)
      && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    middlewares:
      - name: basic-auth
        namespace: admin

extraObjects:
  # Wildcard certificate for production domain
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: wildcard-netcup
    spec:
      secretName: wildcard-netcup-tls
      dnsNames:
        - '*.albertperez.dev'
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer

tlsStore:
  default:
    defaultCertificate:
      secretName: "wildcard-netcup-tls"                