apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`argocd.albertperez.dev`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    certResolver: le
