environments:
  minikube: {}
  netcup: {}

---
repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.18.2
    values:
      - values.yaml
      - ../../envs/{{ .Environment.Name }}/cert-manager-values.yaml
    wait: true
    timeout: 300
    atomic: true
