apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches-traefik.yaml
    target:
      kind: Application
      name: traefik
  - path: patches-hello.yaml
    target:
      kind: Application
      name: hello
  - path: patches-traefik-dashboard.yaml
    target:
      kind: IngressRoute
      name: traefik-dashboard 