environments:
  minikube: {}
  netcup: {}

---
repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

releases:
  - name: sealed-secrets
    namespace: kube-system
    createNamespace: false  # kube-system ya existe
    chart: sealed-secrets/sealed-secrets
    version: 2.15.0  # Corresponde a app version 0.26.0 (tu versión actual)
    values:
      - values.yaml
    timeout: 300 