name: Render Manifests

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Install Helmfile
        run: |
          curl -L https://github.com/helmfile/helmfile/releases/download/v0.162.0/helmfile_0.162.0_linux_amd64.tar.gz | tar xz
          sudo mv helmfile /usr/local/bin/

      - name: Render manifests for minikube
        run: |
          cd infra/apps
          mkdir -p ../rendered/minikube
          helmfile --environment minikube template > ../rendered/minikube/all.yaml

      - name: Render manifests for netcup
        run: |
          cd infra/apps
          mkdir -p ../rendered/netcup
          helmfile --environment netcup template > ../rendered/netcup/all.yaml

      - name: Upload rendered manifests as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests
          path: infra/rendered/ 